### ISSUE TITLE
[enhancement] Compound slug

### ISSUE THREAD

**Issue by ChristherLenander** [ComfortablyCoding/strapi-plugin-slugify#17]
Add an option in the plugin config where you could add fields to put togheter for a slug.
Maybe an array with fieldnames. The order of they are in the array should be how the compund slug is made.

**Comment by ComfortablyCoding** [comment]
That sounds like a useful feature although what would be the expected behaviour when one of the fields is not defined?

Current possible options
1. If any of the fields are missing a value dont apply slugification, this is the current behaviour for the reference field.
2. We skip any fields that are not defined and use the remaining for the slugification.
3. Leave it up to the user with a setting. default would be to skip slugification.

I believe 3 is probably the best option as it provides the ability for the user to decide on which behaviour they prefer.

**Comment by ChristherLenander** [comment]
I agree that 3 is the best.

**Comment by ComfortablyCoding** [comment]
This features has been added in #22 , and will be included in the next release.

**Comment by ChristherLenander** [comment]
👍

**Comment by NidMo** [comment]
> That sounds like a useful feature.
> 
> What would be the expected behaviour when one or more of the fields are not defined?
> 
> Current possible options
> 
> 1. If any of the fields are missing a value dont apply slugification, this is the current behaviour for the reference field.
> 2. We skip any fields that are not defined and use the remaining for the slugification.
> 3. Leave it up to the user with a setting. default would be to skip slugification.
> 
> I believe 3 is probably the best option as it provides the ability for the user to decide on which behaviour they prefer.

how can i skip slugification.

**Comment by ComfortablyCoding** [comment]
If all fields are missing or some are and skip is not true then it should already do this.

I will need to investigate this further.
